
    .weak WWDG_IRQHandler
  .weak PVD_IRQHandler
  .weak TAMPER_IRQHandler
  .weak RTC_IRQHandler
  .weak FLASH_IRQHandler
  .weak RCC_IRQHandler
  .weak EXTI0_IRQHandler
  .weak EXTI1_IRQHandler
  .weak EXTI2_IRQHandler
  .weak EXTI3_IRQHandler
  .weak EXTI4_IRQHandler
  .weak DMA1_Channel1_IRQHandler
  .weak DMA1_Channel2_IRQHandler
  .weak DMA1_Channel3_IRQHandler
  .weak DMA1_Channel4_IRQHandler
  .weak DMA1_Channel5_IRQHandler
  .weak DMA1_Channel6_IRQHandler
  .weak DMA1_Channel7_IRQHandler
  .weak ADC1_2_IRQHandler
  .weak USB_HP_CAN1_TX_IRQHandler
  .weak USB_LP_CAN1_RX0_IRQHandler
  .weak CAN1_RX1_IRQHandler
  .weak CAN1_SCE_IRQHandler
  .weak EXTI9_5_IRQHandler
  .weak TIM1_BRK_IRQHandler
  .weak TIM1_UP_IRQHandler
  .weak TIM1_TRG_COM_IRQHandler
  .weak TIM1_CC_IRQHandler
  .weak TIM2_IRQHandler
  .weak TIM3_IRQHandler
  .weak TIM4_IRQHandler
  .weak I2C1_EV_IRQHandler
  .weak I2C1_ER_IRQHandler
  .weak I2C2_EV_IRQHandler
  .weak I2C2_ER_IRQHandler
  .weak SPI1_IRQHandler
  .weak SPI2_IRQHandler
  .weak USART1_IRQHandler
  .weak USART2_IRQHandler
  .weak USART3_IRQHandler
  .weak EXTI15_10_IRQHandler
  .weak RTC_Alarm_IRQHandler
  .weak USBWakeUp_IRQHandler

  .global WWDG_IRQHandler
  .global PVD_IRQHandler
  .global TAMPER_IRQHandler
  .global RTC_IRQHandler
  .global FLASH_IRQHandler
  .global RCC_IRQHandler
  .global EXTI0_IRQHandler
  .global EXTI1_IRQHandler
  .global EXTI2_IRQHandler
  .global EXTI3_IRQHandler
  .global EXTI4_IRQHandler
  .global DMA1_Channel1_IRQHandler
  .global DMA1_Channel2_IRQHandler
  .global DMA1_Channel3_IRQHandler
  .global DMA1_Channel4_IRQHandler
  .global DMA1_Channel5_IRQHandler
  .global DMA1_Channel6_IRQHandler
  .global DMA1_Channel7_IRQHandler
  .global ADC1_2_IRQHandler
  .global USB_HP_CAN1_TX_IRQHandler
  .global USB_LP_CAN1_RX0_IRQHandler
  .global CAN1_RX1_IRQHandler
  .global CAN1_SCE_IRQHandler
  .global EXTI9_5_IRQHandler
  .global TIM1_BRK_IRQHandler
  .global TIM1_UP_IRQHandler
  .global TIM1_TRG_COM_IRQHandler
  .global TIM1_CC_IRQHandler
  .global TIM2_IRQHandler
  .global TIM3_IRQHandler
  .global TIM4_IRQHandler
  .global I2C1_EV_IRQHandler
  .global I2C1_ER_IRQHandler
  .global I2C2_EV_IRQHandler
  .global I2C2_ER_IRQHandler
  .global SPI1_IRQHandler
  .global SPI2_IRQHandler
  .global USART1_IRQHandler
  .global USART2_IRQHandler
  .global USART3_IRQHandler
  .global EXTI15_10_IRQHandler
  .global RTC_Alarm_IRQHandler
  .global USBWakeUp_IRQHandler

WWDG_IRQHandler:  1:  j 1b
PVD_IRQHandler:  1:  j 1b
TAMPER_IRQHandler:  1:  j 1b
RTC_IRQHandler:  1:  j 1b
FLASH_IRQHandler:  1:  j 1b
RCC_IRQHandler:  1:  j 1b
EXTI0_IRQHandler:  1:  j 1b
EXTI1_IRQHandler:  1:  j 1b
EXTI2_IRQHandler:  1:  j 1b
EXTI3_IRQHandler:  1:  j 1b
EXTI4_IRQHandler:  1:  j 1b
DMA1_Channel1_IRQHandler:  1:  j 1b
DMA1_Channel2_IRQHandler:  1:  j 1b
DMA1_Channel3_IRQHandler:  1:  j 1b
DMA1_Channel4_IRQHandler:  1:  j 1b
DMA1_Channel5_IRQHandler:  1:  j 1b
DMA1_Channel6_IRQHandler:  1:  j 1b
DMA1_Channel7_IRQHandler:  1:  j 1b
ADC1_2_IRQHandler:  1:  j 1b
USB_HP_CAN1_TX_IRQHandler:  1:  j 1b
USB_LP_CAN1_RX0_IRQHandler:  1:  j 1b
CAN1_RX1_IRQHandler:  1:  j 1b
CAN1_SCE_IRQHandler:  1:  j 1b
EXTI9_5_IRQHandler:  1:  j 1b
TIM1_BRK_IRQHandler:  1:  j 1b
TIM1_UP_IRQHandler:  1:  j 1b
TIM1_TRG_COM_IRQHandler:  1:  j 1b
TIM1_CC_IRQHandler:  1:  j 1b
TIM2_IRQHandler:  1:  j 1b
TIM3_IRQHandler:  1:  j 1b
TIM4_IRQHandler:  1:  j 1b
I2C1_EV_IRQHandler:  1:  j 1b
I2C1_ER_IRQHandler:  1:  j 1b
I2C2_EV_IRQHandler:  1:  j 1b
I2C2_ER_IRQHandler:  1:  j 1b
SPI1_IRQHandler:  1:  j 1b
SPI2_IRQHandler:  1:  j 1b
USART1_IRQHandler:  1:  j 1b
USART2_IRQHandler:  1:  j 1b
USART3_IRQHandler:  1:  j 1b
EXTI15_10_IRQHandler:  1:  j 1b
RTC_Alarm_IRQHandler:  1:  j 1b
USBWakeUp_IRQHandler:  1:  j 1b
